<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domin\Domin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Feaures\Location\City\Handlers\Commands\" />
    <Folder Include="Feaures\Location\City\Handlers\Queries\" />
    <Folder Include="Feaures\Location\City\Requests\Commands\" />
    <Folder Include="Feaures\Location\Organization\Handlers\Commands\" />
    <Folder Include="Feaures\Location\Organization\Handlers\Queries\" />
    <Folder Include="Feaures\Location\Organization\Requests\Commands\" />
    <Folder Include="Feaures\Location\Organization\Requests\Queries\" />
    <Folder Include="Feaures\Location\Province\Handlers\Commands\" />
    <Folder Include="Feaures\Location\Province\Handlers\Queries\" />
    <Folder Include="Feaures\Location\Province\Requests\Commands\" />
    <Folder Include="Feaures\Location\Province\Requests\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
