<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\Users\**" />
    <EmbeddedResource Remove="Entities\Users\**" />
    <None Remove="Entities\Users\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Framworks\GenericRepository\GenericRepository.csproj" />
  </ItemGroup>

</Project>
